---
title: "Ape cultures do not require behavior copying"
author: 
  - Alberto Acerbi^[Centre for Culture and Evolution, Division of Psychology, Brunel University London, Uxbridge, UB8 3PH, United Kingdom]
  - William Daniel Snyder, Claudio Tennie^[Faculty of Science, Department for Early Prehistory and Quaternary Ecology, University of Tübingen, Schloß Hohentuebingen, Burgsteige 11, 72070, Tübingen, Germany]
date: ""
output: pdf_document
fontsize: 11pt 
geometry: margin=1in
citecolor: blue
bibliography: ../oranzees/oranzees.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

  While culture is widespread in the animal kingdom, human culture has been claimed to be special due to being cumulative. It is currently debated which cognitive abilities support cumulative culture, but behavior copying is one of the main abilities proposed. One important source of contention is the presence or absence of behavior copying in our closest living relatives, non-human great apes (apes) – especially given that their behavior does not show clear signs of cumulation. Those who claim that apes copy behavior often base this claim on the existence of stable ape cultures in the wild. We developed an individual-based model to test whether ape cultural patterns can both emerge and stabilize in absence of any behavior copying, when only allowing for a well-supported alternative social learning mechanism, socially-mediated reinnovation, where only the frequency of reinnovation is under social influence, but the form of the behavior is not. Our model reflects wild ape life conditions, including physiological and behavioral needs, demographic and spatial features, and possible genetic and ecological variation between populations. Our results show that, under a wide range of values of parameters, we fully reproduce the defining features of wild ape cultural patterns. Overall, our results show that ape cultures can emerge and stabilize without behavior copying. Ape cultures do not show the signatures of behavior copying abilities, lending support to the notion that behavior copying is, among apes, unique in the human lineage. It therefore remains an open question when and why behaviour copying evolved in hominins.
  
## Highlights

  Human culture is cumulative: it grows in complexity and efficiency, drawing on innovations of previous generations. In contrast, ape cultures are not clearly cumulative. It has been proposed that cumulative culture depends on our ability to accurately transmit and preserve information, with behavior copying as a crucial mechanism. At the same time, researchers have claimed that non-human apes can also copy others' behavior. We show, through computer simulations, that patterns used to infer the existence of behavior copying in wild apes – ape cultures – can be reproduced in full, under realistic conditions, without any behavior copying skills necessary. This shows that the mere existence of ape cultures does not prove that they are underlain by behavior copying.
  
#### Keywords

Cultural transmission; cultural evolution; cumulative culture; non-human great ape culture; individual-based models; behavior copying.
  
<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

# Introduction
 
umulative culture, the transmission and improvement of knowledge, technologies, and beliefs from individual to individual, and from generation to generation, is key to explain the extraordinary ecological success of our species [@henrich_secret_2015; @boyd_different_2017]. Which cognitive abilities underpin human's cumulative cultural capacities, and how these abilities affect the evolution of culture itself are among the most pressing questions of evolutionary human science. 

Many species are able to at least use social cues to adjust their behavior. Various ape species have been shown to posses traditions that are socially influenced in this way [@whiten_cultures_1999; @whiten_primate_2000; @van_schaik_orangutan_2003; @robbins_behavioral_2016]. Humans, by contrast, have cumulative culture. While there are various definitions of cumulative culture [@mesoudi_what_2018], some of its characteristics are broadly accepted. Cumulative culture requires the accumulation of cultural traits (more cultural traits are present at generation *g* than at time *g-1*), their improvement (cultural traits at generation *g* are more effective than at generation *g-1*), and ratcheting (the innovation of cultural traits at generation *g* depends on the presence of other traits at generation *g-1*) [@acerbi_cultural_2019]. 

While not all human culture needs to be supported by faithful copying [@morin_how_2015], cumulative culture depends on an ability to accurately transmit and preserve new behaviors. Experiments have indeed shown that humans are capable of copying behaviors, and that they routinely do so cross-culturally [@nielsen_overimitation_2010; @berl_cultural_2015]. More controversial is the claim that other primate species copy behaviors. Arguments regarding the existence of non-human great ape cultures based on behavior copying raise a puzzling question: if other ape species can and do copy behaviors, why do they not develop cumulative cultures? There are only two possible answers to this question: either apes do not copy behavior, or copying behavior does not automatically lead to cumulative culture.

Primatologists have claimed the existence of ape cultures based on the ability of behavior copying, drawing on observations conducted on wild ape populations. For example, researchers examined the population-level distribution of behaviors in populations of chimpanzees across seven sites, and argued that the inter-site differences in the frequency of behaviors proved the existence of behavior copying-based cultures in these populations [@whiten_cultures_1999]. We developed an individual-based model to assess whether these patterns, and similar patterns in orangutans [@van_schaik_orangutan_2003], actually justify the conclusion that behavior copying is the underlying learning mechanism. We reproduced several details of the original study [@whiten_cultures_1999], including realistic demographic and spatial features, and effects of ecological availability and genetic predisposition, to investigate whether an equivalent distribution of behavioral traits could emerge in the absence of any behavior copying. While our hypothetical ape species, *oranzees*, can be influenced by social cues (widespread in the animal kingdom, and certainly present in all apes), we explicitly excluded any behavior copying.

Our results show that, under realistic values of the main parameters, we can reproduce the distribution of behavioral traits found in @whiten_cultures_1999, without any behavior copying required. In other words, as oranzees can and do show cultural patterns resembling wild ape patterns, this shows that such patterns do not allow to conclude that behavior copying must have taken place.

# Materials and methods

We build an individual-based model that reproduces a world inhabited by six populations of "oranzees", a hypothetical ape species. The model is spatially explicit: the oranzees populations are located at relative positions analogous to the six chimpanzees sites in @whiten_cultures_1999. This is important to determine the potential genetic predispositions and ecological availabilities associated with their possible behaviors (see below). Population sizes are also taken from the sites in @whiten_cultures_1999. Following @lind_number_2010, we use data from @wrangham_why_2000, and we define population sizes as $N=\{20;42;49;76;50;95\}$.

Oranzees are subject to an age-dependent birth/death process, broadly inspired by descriptions in @hill_mortality_2001. A time step $t$ of the simulation represents a month in oranzees' life. From when they are 25 years old ($t=300$), there is a 1% probability an oranzee will die each month, or they die when they are 60 years old ($t=720$). The number of individuals in the population is fixed, so each time an oranzee dies it is replaced by a newborn. 

A newborn oranzee does not yet show any behavior. Behaviors can be innovated at each time step. The process of innovation is influenced by: (i) the oranzees ‘state’, which depends on the behaviors an individual already possesses, (ii) the frequency of the behaviors already present in the population ("socially-mediated reinnovation" in @bandini_spontaneous_2017), and (iii) the genetic propensity and ecological availability locally associated with the behavior. At the beginning of the simulations, the populations are randomly initialized with individuals between 0 and 25 years old.

### Oranzees' behaviors and state

In the oranzees' world, 64 behaviors are possible (targeting the 65 behaviors coded in @whiten_cultures_1999, but making it an even number from modelling convenience). Behaviors are divided into two categories: 32 social and 32 food-related behaviors. These figures where chosen to resemble the behavioral categories considered in @whiten_cultures_1999. Behaviors serve oranzees to fulfill various goals. Oranzees have a 'state' that is based on how many goals are fulfilled in the two main categories of social and food-related behaviors.    

In the case of social behaviors, we assume four sub-categories ('play', 'display', 'groom', 'courtship'; note the names are only evocative), each with eight possible different behaviors that serve the same goal. A goal is considered fulfilled if an oranzee shows at least one behavior out of the eight in the sub-category. Oranzees have a 'state' that is based on how many of the four goals are fulfilled. An oranzee has a state value of $0.25$ if, for example, it shows at least one behavior in the category 'play', and none of the others, and a state value of $1$ if it shows at least one behavior in each sub-category. $p_\text{social}$, the probability to innovate a social behavior, is drawn from a normal distribution with mean equal to $1-state_\text{social}$. 

Food-related behaviors are analogously divided into sub-categories. Differently from social behaviors, there is a variable number of behaviors in each sub-category. In addition, sub-categories are associated to two different 'nutrients', *Y* and *Z*. Here individuals need to balance their nutritional intake, so that their optimal diet consist in a roughly equal number of food for one and the other nutrient. The state, for food-related behaviors, depends on the total amount of food ingested *and* on the balance between nutrients. The state is calculated as the sum of each sub-category fulfilled (as above, for this to happen there needs to be at least one behavior present) minus the difference between the number of sub-categories providing nutrient *Y* and the number of sub-categories providing nutrient *Z*. We normalize the state between $0$ and $1$, and, as above, $p_\text{food}$ is then calculated as $1-state_\text{food}$.

### Socially-mediated reinnovation

At each time step, all oranzees have a probability of individual innovation for social and food-related behaviors calculated as described above. The specific behavior an oranzee will innovate depends both on the frequency of the behaviors already present in the population (see below), and on the ecological availability and genetic propensity associated to the behavior. A further parameter of the model, $S$, controls the probability that each reinnovation is socially-mediated [@bandini_spontaneous_2017]. When a reinnovation is socially-mediated, the probability of innovating each behavior $B_i$ is weighted by its proportional instances in the population among the behaviors of the same category (social or food-related). That is, the frequency of behavior can catalyze more individual innovations of the same behavior: common behaviors are more likely to be individually reinnovated.

When the innovation is not socially-mediated, the probability of innovating each behavior is random. Only one behavior per category can be innovated at each time step. 

### Genetic propensity and ecological availability

The behavior selected in the previous step is then innovated or not according to its genetic propensity and, in case of food-related behaviors, ecological availability. 

Genetic propensity is a probability $p_g(0,1)$, assigned independently for each of the 64 behaviors. A parameter of the model, $\alpha_g$, determines the probability that the genetic propensity of each behavior is equal for all the six populations or whether is different. If the probability is equal, $p_g$ is randomly drawn. If it is different, we assign the propensity using a geographical gradient. We choose a random point and calculate its distance to each population. Distances are then transformed to $p_g$ by rescaling them between 0 and 1, so that for the farthest site where $p_g=0$, the associated behavior cannot possibly be expressed (see SI). Notice that $\alpha_g=0$ does not mean that there are no genetic influences on the behavior, but that there are no *differences* between the populations with regard to this aspect.

Ecological availability is a probability $p_e(0,1)$ that represents the likelihood of finding a resource, or its nutritional value, in each site. Ecological availability is assigned only to food-related behaviors, and it is calculated in the same way of $p_g$, using the parameter $\alpha_e$ to determine the probability of ecological availability being different in the six populations.

### Model's output

We run simulations for $t_\text{max}=6000$ (corresponding to 500 years of oranzee-time). For each simulation, following @whiten_cultures_1999, we classify each behavior, in each population, as:

* *customary*: a behavior observed in over 50% of individuals in at least one age class (see SI for how age classes are defined in our model).

* *habitual*: a behavior observed in at least two individuals across the population.

* *present*: a behavior observed in at least one individual across the population.

* *absent*: a behavior not observed even once in the population.

* *ecological explanations*: a behavior that is absent due to a complete lack of local ecological availability (i.e., in our model, associated to $p_e=0$).

Notice that one additional category in @whiten_cultures_1999 (*unknown*, i.e. "the behavior has not been recorded, but this may be due to inadequacy of relevant observational opportunities") does not apply in our case, because we have complete knowledge of the output of the simulations.

Finally, to test how well our model compares to wild apes, we calculate the same "patterns" described in @whiten_cultures_1999:

* *A*: behavior absent at no site.

* *B*: behavior not achieving habitual frequencies at any site.

* *C*: behavior for which any absence can be explained by local ecological factors.

* *D*: behavior customary or habitual at some sites yet absent at others, with no ecological explanation, i.e. behaviors defined as "cultural".

Further details of the model implementation and of how outputs are processed are available in SI. The full code of the model allowing to reproduce all our results, plus a detailed description of the model development is available in a dedicated GitHub repository, at <https://github.com/albertoacerbi/oranzees>. 


# Results

We are particularly interested in the realistic parameter conditions of moderate to high environmental variability (i.e. $\alpha_e$ from 0.5 to 1) and zero to moderate genetic differences (i.e. $\alpha_g$ from 0 to 0.5). We ran 20 simulations for each combination (for a total of 600 runs). For all, reinnovation is socially-mediated ($S=1$). The results show that various combinations of parameters produce a number of cultural behaviors (pattern *D*) consistent with the 38 found in @whiten_cultures_1999, in absence of any explicit copying mechanism being implemented (see Figure \ref{Figure1}). In Figure \ref{Figure2}, we reproduce the output of a run where 38 cultural behaviors were found, and how they were classified in each of the six simulated populations, using a visualization inspired by @whiten_cultures_1999.

![Number of cultural traits in oranzees, when varying ecological and genetic diversity. Red color indicates simulation runs that produced more than 38 cultural traits (the number of cultural traits identified in 1); blue color indicates simulation runs that produced less than 38 cultural traits. For all simulations, $S=1$, $\alpha_e$ and $\alpha_g$ as indicated in the plot. $N=20$ runs for each parameters combination. (See SI for other values of $S$, $\alpha_e$, and $\alpha_g$, including all equal to zero.)\label{Figure1} ](../oranzees/figures/figure_1){width=70%}

![Example of a simulation run that produces 38 cultural traits ($S=1$, $\alpha_e=0.8$, and $\alpha_g=0.2$). Color icons indicate customary behaviors; circular icons, habitual; monochrome icons, present; clear, absent;  horizontal bar, absent with ecological explanation. The names of the behaviors are only evocative, see SI for a complete list.\label{Figure2} ](../oranzees/figures/figure_2){width=80%}

We also analysed the effect of the parameter $S$ (proportion of socially-mediated reinnovations), in three conditions (see Figure S4): (a) no genetic differences and intermediate ecological differences (compare to the high-left corner of Figure \ref{Figure1}, where with $S=1$ simulations produce less than 38 cultural behaviors), (b) one of the conditions that produce good match with @whiten_cultures_1999, namely $\alpha_e=0.8$ and $\alpha_g=0.2$, and (c) intermediate genetic differences and high ecological differences (compare to the low-right corner of Figure \ref{Figure1}, where with $S=1$ simulations produce more than 38 cultural behaviors). As expected, decreasing *S* decreases the number of cultural behaviors. Conditions where, with $S=1$, there were more than 38 cultural behaviors could still produce results analogous to @whiten_cultures_1999, given that not all reinnovations are socially mediated.

As a further proof of our model's fit with empirical data, our outputs not only accurately reproduce the number of cultural behaviors (pattern *D*), but also the number of behaviors classified in the other three patterns (*A*, *B*, *C*, see above) in @whiten_cultures_1999 (see Figure S5).

Finally, we ran 100 simulations for one of the conditions where we have a good match for the number of cultural behaviors in @whiten_cultures_1999 ($\alpha_e=0.8;\alpha_g=0.2, S=1$). In each simulation, we recorded, for each population, the number of behaviors (habitual + customary + present) that are also classified as cultural (see Figure S6). We find a small, but significant, correlation between population size and number of cultural traits ($p<0.00001,\rho=0.2,N=600$). In other words, our model reproduces an effect of cultural accumulation (i.e. increased number of expressed behaviors) relative to population size possibly found in real populations - see [@whiten_evolution_2007; @lind_number_2010; @kuhl_human_2019] - again, in the absence of behavior copying.

# Discussion

We developed an individual-based model to examine under which conditions a distribution of cultural traits analogous to the distribution reported in @whiten_cultures_1999 in chimpanzees could emerge, crucially, without allowing for the existence of any behavior copying mechanism. We implemented several details of the original wild ape study, including realistic demographic and spatial features, as well as effects of genetic propensity and ecological availability on the behaviors. Given the widespread availability of non-copying variants of social learning across the animal kingdom, we also included socially-mediated reinnovation, where social learning merely catalyzes individual reinnovation, without any behavior copying [@bandini_spontaneous_2017].

Our main result is that we can reproduce the general pattern observed in populations of wild apes under realistic values of the parameters of genetic propensity and ecological availability, namely zero to medium importance of genetic variation, and medium to high importance of ecological variation. (Notice however that even in the entire absence of any ecological and genetic variation, i.e. with $\alpha_e=0$ and $\alpha_g=0$, some cultural traits occur, see Figure S7). Our model cannot precisely determine which exact values of these parameters produce the patterns of real populations of chimpanzees (or other apes). However, we are confident that the range of values we explored, and the ease by which patterns of cultural behaviors similar to @whiten_cultures_1999 can be produced, show that behavior copying is not logically required for such patterns to emerge. Therefore, ape-like cultural patterns [@whiten_cultures_1999; @van_schaik_orangutan_2003; @robbins_behavioral_2016] do not and cannot pinpoint behavior copying abilities. In addition, and as further support for our results, our model not only reproduces the ape cultural behavioral patterns, but also the proportions among the other patterns observed in wild apes, i.e. absent behaviors, behaviors not achieving habitual frequencies at any site, and behaviors absent because of ecological factors.   

In our model, we focused on the mechanism of socially mediated reinnovation, that is, we assumed that members of our hypothetical species, oranzees, had a probability to individually reinnovate a specific behavior stochastically linked to how many other oranzees in the population were already showing this behavior. While this is a realistic assumption [@tennie_evidence_2010] and while it reproduces in our model the chimpanzees' cultural pattern observed in realistic conditions, our results demonstrate even this is not always necessary. Given certain combinations of parameters, such as higher genetic and ecological diversities, the same population level pattern can be obtained even when reinnovation is not socially mediated, i.e. when oranzees are not influenced by the behaviors of the other individuals in their populations (compare figure S4). That is, similar patterns can exist when the underpinning individual-level mechanisms are not cultural even in a minimal way [@neadle_food_2017]. However, socially mediated reinnovation is likely required to explain observed differences in behavioral frequencies between the subset of ape populations that exist in genetic contact and that share similar environments [@langergraber_genetic_2011].

Finally, our model reproduces a reported correlation between population size and number of cultural traits in the six populations [@whiten_evolution_2007; @lind_number_2010; @kuhl_human_2019]. The magnitude of the effect is small, which is to be expected, given that the presence of this correlation in real populations of (human and non-human) apes is currently debated [@vaesen_population_2016]. Notice that this correlation too is brought about without any behavior copying, so that there is no need to invoke reasons concerning details of cultural transmssion (e.g. @henrich_demography_2004) to explain such a pattern.

More generally, the results of our models suggest caution when deriving individual-level mechanisms from population-level patterns (see also [@acerbi_conformity_2016; @barrett_equifinality_2019]). Cultural systems, as many others, exhibit equifinality: the same global state can be produced by different local underlying processes. Models and experiments are crucial to test the plausibility of inferences going from global to local properties.   

In conclusion, our model strongly suggests that the data available on the behavioral distributions of apes populations cannot demonstrate that ape possess cultures influenced by behavior copying, let alone *requiring* behavior copying. This, in turn, may provide an explanation to why ape cultures are not cumulative: as cumulative culture requires at minimum behavior copying, we should not expect any species lacking this mechanism to develop it. Given the phylogenetic closeness of apes to the human lineage, our results speak also of the likely absence of behavior copying of the last common ancestor of apes and humans [@tennie_early_2017]. 

### *Acknowledgements*

This project has received funding from the European Research Council (ERC) under the European Union's Horizon 2020 research and innovation programme (grant agreement n° 714658; STONECULT project). We would like to than Mima Batalovic for the support provided, and Elisa Bandini, Alba Motes Rodrigo, and Jonathan Reeves for comments on earlier versions of the manuscript.

# References

